# Generated by Django 2.2.7 on 2019-11-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('federal_or_state', models.CharField(choices=[('FD', 'Federal'), ('ST', 'State')], max_length=2)),
                ('size_in_acres', models.IntegerField(default=0)),
                ('annual_visitors', models.IntegerField(default=0)),
                ('average_annual_fire_coverage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.State')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=80)),
                ('ammended', models.BooleanField(default=False, verbose_name='ammended?')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Park')),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.Region'),
        ),
    ]
