# Generated by Django 2.2.7 on 2019-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20191121_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='link',
            field=models.CharField(blank=True, max_length=120, verbose_name='Link to Online Copy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='pdf',
            field=models.FileField(blank=True, upload_to='policypdfs/', verbose_name='PDF'),
        ),
    ]
